'use strict';

const SUPABASE_URL='https://aanxpugvehwtcwwpefwx.supabase.co';
const SUPABASE_KEY='sb_publishable_ICMR8EF0LK69VjfVRWe0ew_120LIV7A';
const VAPID_PUBLIC='BJYpdEsob-TJHXH5cn27pxwAgHZRVKTetdZraQO5LVmcwQYUzkYR3bQ0wc57jxlxWajOTYfOfanDlWJmTI-cRzY';
const APP_URL='https://karlkirch.github.io/Crossfit/';
const APP_VERSION='4.0';
const TZ='Europe/Tallinn';

const root=document.getElementById('appRoot');
const toastEl=document.getElementById('toast');
const updateBanner=document.getElementById('updateBanner');
const updateNow=document.getElementById('updateNow');

const state={
  mode:'login',session:null,profile:null,view:'home',trainingTab:'upcoming',
  trainings:[],registrations:[],profiles:[],wallets:[],creditTransactions:[],
  packageTypes:[],userPackages:[],notifications:[],
  modal:null,modalData:null,loading:false,installPrompt:null,swReg:null,pushBusy:false
};

const icon={
  home:'<svg viewBox="0 0 24 24"><path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/></svg>',
  dumbbell:'<svg viewBox="0 0 24 24"><path d="M6 8v8M3.5 9.5v5M18 8v8M20.5 9.5v5M6 12h12"/></svg>',
  user:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4.5 20c.8-4 3.3-6 7.5-6s6.7 2 7.5 6"/></svg>',
  users:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3.2"/><circle cx="17" cy="9" r="2.5"/><path d="M3.5 19c.7-3.5 2.6-5.3 5.5-5.3s4.8 1.8 5.5 5.3M14.5 14.3c2.8-.2 4.8 1.4 5.5 4.7"/></svg>',
  bell:'<svg viewBox="0 0 24 24"><path d="M6 9a6 6 0 0 1 12 0c0 7 3 7 3 8H3c0-1 3-1 3-8"/><path d="M10 20h4"/></svg>',
  more:'<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1.2"/><circle cx="12" cy="12" r="1.2"/><circle cx="19" cy="12" r="1.2"/></svg>',
  plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',
  copy:'<svg viewBox="0 0 24 24"><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/></svg>',
  package:'<svg viewBox="0 0 24 24"><path d="m4 7 8-4 8 4-8 4-8-4Z"/><path d="m4 7v10l8 4 8-4V7M12 11v10"/></svg>',
  share:'<svg viewBox="0 0 24 24"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.7 10.6 6.6-4M8.7 13.4l6.6 4"/></svg>',
  info:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7.5h.01"/></svg>',
  logout:'<svg viewBox="0 0 24 24"><path d="M10 5H5v14h5M14 8l4 4-4 4M18 12H9"/></svg>',
  edit:'<svg viewBox="0 0 24 24"><path d="M4 20h4L19 9l-4-4L4 16v4Z"/><path d="m13.5 6.5 4 4"/></svg>',
  calendar:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18"/></svg>',
  chevron:'<svg viewBox="0 0 24 24"><path d="m9 6 6 6-6 6"/></svg>',
  settings:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1A7 7 0 0 0 15 6l-.3-2.6h-4L10.4 6A7 7 0 0 0 8.8 7l-2.4-1-2 3.4 2 1.5a7 7 0 0 0 0 2L4.4 14l2 3.4 2.4-1A7 7 0 0 0 10.4 18l.3 2.6h4L15 18a7 7 0 0 0 1.6-1l2.4 1 2-3.4-2-1.5a7 7 0 0 0 .1-1Z"/></svg>'
};

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(c){return (Number(c||0)/100).toFixed(2).replace('.',',')+' €'}
function toast(text){toastEl.textContent=text;toastEl.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toastEl.classList.remove('show'),2600)}
function dateTime(iso){return new Intl.DateTimeFormat('et-EE',{timeZone:TZ,weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(iso))}
function fullDateTime(iso){return new Intl.DateTimeFormat('et-EE',{timeZone:TZ,weekday:'long',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(iso))}
function shortDate(iso){return new Intl.DateTimeFormat('et-EE',{timeZone:TZ,day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(iso))}
function now(){return new Date()}
function isTrainer(){return state.profile?.role==='trainer'}
function pname(id){return state.profiles.find(p=>p.user_id===id)?.display_name||'Kasutaja'}
function regsFor(tid){return state.registrations.filter(r=>r.training_id===tid)}
function confirmedFor(tid){return regsFor(tid).filter(r=>r.status==='confirmed')}
function waitlistFor(tid){return regsFor(tid).filter(r=>r.status==='waitlist').sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)||a.id-b.id)}
function mineFor(tid){return regsFor(tid).find(r=>r.user_id===state.session?.user?.id&&['confirmed','waitlist'].includes(r.status))}
function mineAnyFor(tid){return regsFor(tid).find(r=>r.user_id===state.session?.user?.id)}
function upcomingTrainings(){return state.trainings.filter(t=>t.status==='published'&&new Date(t.starts_at)>now()).sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at))}
function pastTrainings(){return state.trainings.filter(t=>new Date(t.starts_at)<=now()||t.status==='cancelled').sort((a,b)=>new Date(b.starts_at)-new Date(a.starts_at))}
function activeUserPackages(uid=state.session?.user?.id){const n=Date.now();return state.userPackages.filter(p=>p.user_id===uid&&p.status==='active'&&(!p.expires_at||new Date(p.expires_at).getTime()>=n)&&(p.kind==='unlimited'||Number(p.credits_remaining)>0))}
function legacyCredits(uid=state.session?.user?.id){return Number(state.wallets.find(w=>w.user_id===uid)?.credits||0)}
function totalCredits(uid=state.session?.user?.id){const p=activeUserPackages(uid);if(p.some(x=>x.kind==='unlimited'))return Infinity;return legacyCredits(uid)+p.reduce((s,x)=>s+Number(x.credits_remaining||0),0)}
function paymentPill(status){const map={paid:['Tasutud','green'],package:['Pakett','blue'],unpaid:['Tasumata','amber'],refund_pending:['Tagastus ootel','amber'],refunded:['Tagastatud','green'],pending:['Ootel','amber']};const x=map[status]||[status||'—',''];return `<span class="pill ${x[1]}">${esc(x[0])}</span>`}
function packageStatus(p){if(p.status==='cancelled')return['Tühistatud','red'];if(p.expires_at&&new Date(p.expires_at)<now())return['Aegunud','red'];if(p.status==='exhausted'||(p.kind==='credits'&&Number(p.credits_remaining)<=0))return['Kasutatud',''];return['Aktiivne','green']}
function cancellationDeadline(t){return new Date(new Date(t.starts_at).getTime()-Number(t.cancellation_hours||0)*3600000)}
function cancellationRule(t){return `Tasuta tühistamine kuni ${t.cancellation_hours} h enne treeningut. Hilisema tühistamise korral kasutatud treeningkorda või tasu ei tagastata.`}
function waitPosition(tid,uid=state.session?.user?.id){const w=waitlistFor(tid);const i=w.findIndex(r=>r.user_id===uid);return i<0?null:i+1}

function headers(token){const h={'apikey':SUPABASE_KEY,'Content-Type':'application/json'};if(token)h.Authorization='Bearer '+token;return h}
async function request(url,opt={}){const r=await fetch(url,opt);const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch(_){data=text}if(!r.ok){const msg=(data&&typeof data==='object'&&(data.message||data.msg||data.error_description||data.error||data.hint))||text||`HTTP ${r.status}`;throw new Error(msg)}return data}
async function api(path,opt={}){if(!state.session?.access_token)throw new Error('Sessioon puudub');return request(`${SUPABASE_URL}/rest/v1/${path}`,{...opt,headers:{...headers(state.session.access_token),...(opt.headers||{})}})}
async function rpc(name,body={}){return api(`rpc/${name}`,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(body)})}
function authError(msg){const s=String(msg||'');if(/invalid login credentials/i.test(s))return 'E-post või parool on vale.';if(/email not confirmed/i.test(s))return 'E-post ei ole kinnitatud. Ava kinnituskiri ja proovi uuesti.';if(/already registered|duplicate key|already exists/i.test(s))return 'Selle e-postiga konto on juba olemas.';return s||'Toiming ebaõnnestus.'}

async function refreshSession(){if(!state.session?.refresh_token)return false;try{const data=await request(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:headers(),body:JSON.stringify({refresh_token:state.session.refresh_token})});state.session=data;localStorage.setItem('wod_session',JSON.stringify(data));return true}catch(_){state.session=null;localStorage.removeItem('wod_session');return false}}
async function ensureProfile(){let rows=await api(`wod_profiles?select=user_id,display_name,role&user_id=eq.${state.session.user.id}`);if(!rows?.length){const name=(state.session.user.user_metadata?.display_name||state.session.user.email?.split('@')[0]||'Kasutaja').trim();await rpc('wod_ensure_profile',{new_display_name:name});rows=await api(`wod_profiles?select=user_id,display_name,role&user_id=eq.${state.session.user.id}`)}state.profile=rows[0]}
async function loadData(){
  const since=new Date(Date.now()-365*86400000).toISOString();
  const trainer=isTrainer();
  const uid=state.session.user.id;
  const queries=[
    api(`wod_trainings?select=*&starts_at=gte.${encodeURIComponent(since)}&order=starts_at.asc`),
    api('wod_registrations?select=*&order=created_at.asc'),
    api('wod_profiles?select=user_id,display_name,role&order=display_name.asc'),
    api(trainer?'wod_wallets?select=user_id,credits':`wod_wallets?select=user_id,credits&user_id=eq.${uid}`),
    api(trainer?'wod_credit_transactions?select=*&order=created_at.desc&limit=200':`wod_credit_transactions?select=*&user_id=eq.${uid}&order=created_at.desc&limit=50`),
    api('wod_package_types?select=*&order=sort_order.asc,id.asc'),
    api(trainer?'wod_user_packages?select=*&order=purchased_at.desc':`wod_user_packages?select=*&user_id=eq.${uid}&order=purchased_at.desc`),
    api(`wod_notifications?select=*&user_id=eq.${uid}&order=created_at.desc&limit=80`)
  ];
  const [t,r,p,w,tx,pt,up,n]=await Promise.all(queries);
  state.trainings=t||[];state.registrations=r||[];state.profiles=p||[];state.wallets=w||[];state.creditTransactions=tx||[];state.packageTypes=pt||[];state.userPackages=up||[];state.notifications=(n||[]).filter(x=>!x.due_at||new Date(x.due_at)<=now());
}
async function reloadData(message){try{state.loading=true;await loadData();render();if(message)toast(message)}catch(e){toast(e.message||'Andmete uuendamine ebaõnnestus')}finally{state.loading=false}}

function navButton(view,label,svg,badge=''){return `<button class="nav-btn ${state.view===view?'on':''}" onclick="go('${view}')">${svg}<span>${label}</span>${badge?`<span class="nav-badge">${badge}</span>`:''}</button>`}
function unreadCount(){return state.notifications.filter(n=>!n.read_at).length}
function renderShell(content){
  const trainer=isTrainer();
  const badge=unreadCount();
  root.innerHTML=`<div class="app-shell">
    <header class="topbar"><div class="brand-wrap"><div class="brand-mark">CF</div><div><div class="brand">CrossFit</div><div class="brand-sub">${trainer?'Treeneri vaade':esc(state.profile?.display_name||'')}</div></div></div><button class="top-action" onclick="reloadData('Andmed uuendatud')">Uuenda</button></header>
    <main class="main">${content}</main>
    ${trainer?`<button class="fab" aria-label="Kiirtoimingud" onclick="openQuickActions()">+</button>`:''}
    <nav class="bottom-nav">
      ${navButton('home','Avaleht',icon.home)}
      ${navButton('trainings','Treeningud',icon.dumbbell)}
      ${navButton('people',trainer?'Kliendid':'Minu',trainer?icon.users:icon.user)}
      ${navButton('notifications','Teavitused',icon.bell,badge>9?'9+':badge||'')}
      ${navButton('more','Veel',icon.more)}
    </nav>
  </div>${renderModal()}`;
  updatePushStateSoon();
}
function go(view){state.view=view;state.modal=null;state.modalData=null;window.scrollTo({top:0,behavior:'instant'});render()}

function render(){if(!state.session||!state.profile){renderAuth();return}let content='';if(state.view==='home')content=renderHome();else if(state.view==='trainings')content=renderTrainings();else if(state.view==='people')content=isTrainer()?renderClients():renderMine();else if(state.view==='notifications')content=renderNotifications();else content=renderMore();renderShell(content)}

function renderAuth(){
  const signup=state.mode==='signup';
  root.innerHTML=`<div class="auth"><div class="auth-box"><div class="auth-logo">CF</div><h1>CrossFit</h1><p class="auth-intro">Treeningud, registreerimine, paketid ja teavitused ühes kohas.</p><div class="auth-card"><div class="tabs"><button class="${signup?'':'on'}" onclick="setAuthMode('login')">Logi sisse</button><button class="${signup?'on':''}" onclick="setAuthMode('signup')">Loo konto</button></div><div id="authMessage"></div><div class="form">${signup?'<div class="field"><label>Ees- ja perekonnanimi</label><input id="authName" autocomplete="name"></div>':''}<div class="field"><label>E-post</label><input id="authEmail" type="email" autocomplete="email"></div><div class="field"><label>Parool</label><input id="authPassword" type="password" autocomplete="current-password"></div><button id="authSubmitBtn" class="btn btn-primary btn-block" onclick="submitAuth()">${signup?'Loo konto':'Logi sisse'}</button></div></div></div></div>`;
}
function setAuthMode(mode){state.mode=mode;renderAuth()}
function authMessage(text,bad=false){const e=document.getElementById('authMessage');if(e)e.innerHTML=text?`<div class="notice ${bad?'bad':''}">${esc(text)}</div>`:''}
async function submitAuth(){const email=document.getElementById('authEmail')?.value.trim(),password=document.getElementById('authPassword')?.value,name=document.getElementById('authName')?.value.trim();if(!email||!password||(state.mode==='signup'&&!name)){authMessage('Täida kõik väljad.',true);return}const b=document.getElementById('authSubmitBtn');b.disabled=true;authMessage('Palun oota…');try{let data;if(state.mode==='signup'){data=await request(`${SUPABASE_URL}/auth/v1/signup?redirect_to=${encodeURIComponent(APP_URL)}`,{method:'POST',headers:headers(),body:JSON.stringify({email,password,data:{display_name:name}})});if(!data.access_token){authMessage('Konto loodud. Kinnita e-postis saadetud link ja logi seejärel sisse.');return}}else data=await request(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:headers(),body:JSON.stringify({email,password})});state.session=data;localStorage.setItem('wod_session',JSON.stringify(data));await ensureProfile();await loadData();state.view='home';render()}catch(e){authMessage(authError(e.message),true)}finally{if(b)b.disabled=false}}

function metric(value,label){return `<div class="metric"><b>${value}</b><span>${label}</span></div>`}
function trainerAttention(){const future=upcomingTrainings();const unpaid=state.registrations.filter(r=>r.status==='confirmed'&&r.payment_status==='unpaid'&&future.some(t=>t.id===r.training_id)).length;const waiting=state.registrations.filter(r=>r.status==='waitlist'&&future.some(t=>t.id===r.training_id)).length;const clients=state.profiles.filter(p=>p.role==='client').length;return {unpaid,waiting,clients}}
function clientStats(){const uid=state.session.user.id;const my=state.registrations.filter(r=>r.user_id===uid);const future=my.filter(r=>r.status==='confirmed'&&state.trainings.some(t=>t.id===r.training_id&&new Date(t.starts_at)>now()&&t.status==='published')).length;const attended=my.filter(r=>r.status==='confirmed'&&state.trainings.some(t=>t.id===r.training_id&&new Date(t.starts_at)<now()&&t.status!=='cancelled')).length;return {future,attended}}
function nextClientTraining(){const uid=state.session.user.id;const regIds=new Set(state.registrations.filter(r=>r.user_id===uid&&r.status==='confirmed').map(r=>r.training_id));return upcomingTrainings().find(t=>regIds.has(t.id))||upcomingTrainings()[0]||null}
function renderHome(){
  if(isTrainer()){
    const next=upcomingTrainings()[0],att=trainerAttention();
    return `<div class="page-head"><div><h1 class="page-title">Avaleht</h1><div class="page-sub">Kiire ülevaade tänastest ja järgmistest tegevustest.</div></div></div>
      ${next?`<div class="hero"><div class="hero-kicker">Järgmine treening</div><h1>${esc(next.title)}</h1><p>${esc(fullDateTime(next.starts_at))}</p><div class="hero-actions"><button class="btn btn-primary" onclick="openTraining(${next.id})">Ava treening</button><span class="pill dark">${confirmedFor(next.id).length}/${next.capacity} kohta</span>${waitlistFor(next.id).length?`<span class="pill amber">${waitlistFor(next.id).length} ootel</span>`:''}</div></div>`:`<div class="hero"><div class="hero-kicker">Treeneri vaade</div><h1>Treeninguid pole veel lisatud</h1><p>Lisa esimene treening kiirtoimingust.</p><div class="hero-actions"><button class="btn btn-primary" onclick="openTrainingForm()">Lisa treening</button></div></div>`}
      <div class="metric-grid">${metric(att.unpaid,'Tasumata tulevasi')}${metric(att.waiting,'Ootenimekirjas')}${metric(att.clients,'Kliente')}</div>
      <div class="section"><h2>Kiirtoimingud</h2></div><div class="quick-grid"><button class="quick" onclick="openTrainingForm()">${icon.plus}<b>Lisa treening</b><span>Üksik või korduv treening</span></button><button class="quick" onclick="copyLatestTraining()">${icon.copy}<b>Kopeeri eelmine</b><span>Loo sarnane treening kiiresti</span></button><button class="quick" onclick="go('people');toast('Vali klient ja lisa talle pakett')">${icon.package}<b>Lisa kliendile pakett</b><span>Halda kaarte ja kuupakette</span></button></div>
      ${next?`<div class="section"><h2>Täituvus</h2><small>${confirmedFor(next.id).length} registreerunud</small></div>${trainingCard(next,true)}`:''}`;
  }
  const next=nextClientTraining(),stats=clientStats(),credits=totalCredits();
  const mine=next?mineFor(next.id):null;
  return `<div class="page-head"><div><h1 class="page-title">Tere, ${esc(state.profile.display_name.split(' ')[0])}</h1><div class="page-sub">Siin on sinu järgmine oluline treeninguinfo.</div></div></div>
    ${next?`<div class="hero"><div class="hero-kicker">${mine?'Sinu järgmine treening':'Järgmine vaba treening'}</div><h1>${esc(next.title)}</h1><p>${esc(fullDateTime(next.starts_at))} · ${confirmedFor(next.id).length}/${next.capacity} kohta</p><div class="hero-actions"><button class="btn btn-primary" onclick="openTraining(${next.id})">${mine?'Vaata registreeringut':'Vaata ja registreeru'}</button>${mine?.status==='waitlist'?`<span class="pill amber">Ootenimekiri #${waitPosition(next.id)}</span>`:mine?'<span class="pill green">Registreeritud</span>':''}</div></div>`:`<div class="hero"><div class="hero-kicker">CrossFit</div><h1>Uusi treeninguid pole veel</h1><p>Kui treener lisab uue aja, näed seda siin.</p></div>`}
    <div class="metric-grid">${metric(stats.future,'Tulevast broneeringut')}${metric(stats.attended,'Osaletud treeningut')}${metric(credits===Infinity?'∞':credits,'Treeningkorda alles')}</div>
    <div class="section"><h2>Järgmised treeningud</h2><button class="btn-link" onclick="go('trainings')">Vaata kõiki</button></div><div class="stack">${upcomingTrainings().slice(0,3).map(t=>trainingCard(t,false)).join('')||'<div class="empty">Treeninguid pole veel lisatud.</div>'}</div>`;
}

function trainingCard(t,trainer=isTrainer()){
  const c=confirmedFor(t.id).length,w=waitlistFor(t.id).length,m=mineFor(t.id),pct=Math.min(100,Math.round((c/Math.max(1,t.capacity))*100));
  return `<div class="training-card" onclick="openTraining(${t.id})"><div class="training-top"><div><div class="training-title">${esc(t.title)}</div><div class="training-time">${esc(dateTime(t.starts_at))}</div></div><span class="pill ${c>=t.capacity?'amber':'green'}">${c}/${t.capacity}</span></div><div class="training-meta"><span class="pill">${money(t.price_cents)}</span><span class="pill">${t.duration_minutes} min</span>${w?`<span class="pill amber">Ootel ${w}</span>`:''}${!trainer&&m?`<span class="pill ${m.status==='waitlist'?'amber':'green'}">${m.status==='waitlist'?'Ootenimekiri #'+waitPosition(t.id):'Registreeritud'}</span>`:''}</div><div class="progress ${c<t.capacity?'green':''}"><span style="width:${pct}%"></span></div></div>`;
}

function renderTrainings(){const list=state.trainingTab==='upcoming'?upcomingTrainings():pastTrainings();return `<div class="page-head"><div><h1 class="page-title">Treeningud</h1><div class="page-sub">Vaata treeninguid, registreeru või halda aegu.</div></div>${isTrainer()?'<button class="page-action" onclick="openTrainingForm()">+ Lisa</button>':''}</div><div class="segment"><button class="${state.trainingTab==='upcoming'?'on':''}" onclick="setTrainingTab('upcoming')">Tulevased</button><button class="${state.trainingTab==='past'?'on':''}" onclick="setTrainingTab('past')">Möödunud</button></div><div class="stack">${list.map(t=>trainingCard(t)).join('')||'<div class="empty">Selles vaates treeninguid ei ole.</div>'}</div>`}
function setTrainingTab(tab){state.trainingTab=tab;render()}

function renderMine(){const uid=state.session.user.id;const myRegs=state.registrations.filter(r=>r.user_id===uid);const future=myRegs.filter(r=>['confirmed','waitlist'].includes(r.status)&&state.trainings.some(t=>t.id===r.training_id&&new Date(t.starts_at)>now())).sort((a,b)=>new Date(state.trainings.find(t=>t.id===a.training_id)?.starts_at)-new Date(state.trainings.find(t=>t.id===b.training_id)?.starts_at));const past=myRegs.filter(r=>state.trainings.some(t=>t.id===r.training_id&&new Date(t.starts_at)<=now())).sort((a,b)=>new Date(state.trainings.find(t=>t.id===b.training_id)?.starts_at)-new Date(state.trainings.find(t=>t.id===a.training_id)?.starts_at));const pkgs=state.userPackages.filter(p=>p.user_id===uid);return `<div class="page-head"><div><h1 class="page-title">Minu</h1><div class="page-sub">Sinu paketid, tulevased broneeringud ja treeninguajalugu.</div></div></div><div class="card"><div class="card-title-row"><div><div class="card-title">${esc(state.profile.display_name)}</div><div class="card-sub">${esc(state.session.user.email||'')}</div></div><button class="btn btn-soft btn-sm" onclick="openProfileEdit()">Muuda</button></div></div><div class="section"><h2>Minu paketid</h2></div><div class="stack">${pkgs.map(packageCard).join('')}${legacyCredits(uid)>0?`<div class="package-card"><div class="package-top"><div><div class="package-name">Varasemad treeningkorrad</div><div class="package-meta">Kehtivusajata krediidijääk</div></div><div class="package-balance">${legacyCredits(uid)}</div></div></div>`:''}${!pkgs.length&&!legacyCredits(uid)?'<div class="empty">Sul ei ole aktiivseid pakette.</div>':''}</div><div class="section"><h2>Tulevased registreeringud</h2></div><div class="stack">${future.map(r=>registrationRow(r)).join('')||'<div class="empty">Tulevasi registreeringuid ei ole.</div>'}</div><div class="section"><h2>Treeningute ajalugu</h2></div><div class="stack">${past.slice(0,20).map(r=>registrationRow(r,true)).join('')||'<div class="empty">Ajalugu on veel tühi.</div>'}</div>`}
function packageCard(p){const s=packageStatus(p),balance=p.kind==='unlimited'?'∞':p.credits_remaining;return `<div class="package-card"><div class="package-top"><div><div class="package-name">${esc(p.package_name)}</div><div class="package-meta">${p.expires_at?'Kehtib kuni '+shortDate(p.expires_at):'Kehtivusajata'} · ${money(p.price_paid_cents)}</div></div><div class="package-balance">${balance}</div></div><div class="package-grid"><div class="package-chip"><b>${p.kind==='unlimited'?'Piiramatu':`${p.credits_remaining}/${p.credits_total}`}</b><span>${p.kind==='unlimited'?'Treeninguid':'Kordi alles'}</span></div><div class="package-chip"><b><span class="pill ${s[1]}">${s[0]}</span></b><span>Staatus</span></div></div></div>`}
function registrationRow(r,past=false){const t=state.trainings.find(x=>x.id===r.training_id);if(!t)return'';let status='';if(r.status==='waitlist')status=`<span class="pill amber">Ootenimekiri #${waitPosition(t.id,r.user_id)||'—'}</span>`;else if(r.status==='cancelled'&&r.cancelled_late)status='<span class="pill red">Hilinenud tühistus</span>';else if(r.status==='cancelled')status='<span class="pill red">Tühistatud</span>';else if(past)status='<span class="pill green">Osales</span>';else status='<span class="pill green">Registreeritud</span>';return `<div class="training-card" onclick="openTraining(${t.id})"><div class="training-top"><div><div class="training-title">${esc(t.title)}</div><div class="training-time">${esc(dateTime(t.starts_at))}</div></div>${status}</div><div class="training-meta">${paymentPill(r.payment_status)}</div></div>`}

function renderClients(){const clients=state.profiles.filter(p=>p.role==='client');return `<div class="page-head"><div><h1 class="page-title">Kliendid</h1><div class="page-sub">Kliendikaardid, paketid, krediidid ja makseinfo.</div></div></div><div class="section"><h2>Paketid</h2><button class="btn-link" onclick="openPackageTypeForm()">+ Lisa pakett</button></div><div class="stack">${state.packageTypes.map(packageTypeRow).join('')||'<div class="empty">Pakette pole veel loodud.</div>'}</div><div class="section"><h2>Kliendid</h2><small>${clients.length}</small></div><div class="stack">${clients.map(clientCard).join('')||'<div class="empty">Kliente pole veel.</div>'}</div>`}
function packageTypeRow(p){return `<div class="package-card"><div class="package-top"><div><div class="package-name">${esc(p.name)}</div><div class="package-meta">${p.kind==='unlimited'?'Piiramatu':p.credits+' korda'} · ${p.validity_days?p.validity_days+' päeva':'kehtivusajata'} · ${p.active?'aktiivne':'peidetud'}</div></div><div class="package-balance">${money(p.price_cents)}</div></div><div class="training-actions"><button class="btn btn-soft btn-sm" onclick="event.stopPropagation();openPackageTypeForm(${p.id})">Muuda</button></div></div>`}
function clientCard(p){const uid=p.user_id;const pkgs=activeUserPackages(uid),unpaid=state.registrations.filter(r=>r.user_id===uid&&r.status==='confirmed'&&r.payment_status==='unpaid').length,attended=state.registrations.filter(r=>r.user_id===uid&&r.status==='confirmed'&&state.trainings.some(t=>t.id===r.training_id&&new Date(t.starts_at)<now()&&t.status!=='cancelled')).length;const credits=totalCredits(uid);return `<div class="client-card"><div class="client-top"><div><div class="client-name">${esc(p.display_name)}</div><div class="client-meta">${attended} osaletud treeningut</div></div><span class="pill ${unpaid?'amber':'green'}">${unpaid?unpaid+' tasumata':'Maksed korras'}</span></div><div class="client-summary"><span class="pill blue">${credits===Infinity?'∞':credits} korda</span>${pkgs.slice(0,2).map(x=>`<span class="pill">${esc(x.package_name)}</span>`).join('')}</div><div class="client-actions"><button class="btn btn-soft" onclick="openClient('${uid}')">Kliendikaart</button><button class="btn btn-primary" onclick="openAssignPackage('${uid}')">Lisa pakett</button></div></div>`}

function renderNotifications(){const unread=unreadCount();return `<div class="page-head"><div><h1 class="page-title">Teavitused</h1><div class="page-sub">Push-teavitused ja viimaste teadete ajalugu.</div></div>${unread?'<button class="page-action" onclick="markNotificationsRead()">Märgi loetuks</button>':''}</div><div id="pushCard" class="card"><div class="card-title-row"><div><div class="card-title">Push-teavitused</div><div id="pushText" class="card-sub">Kontrollin teavituste olekut…</div></div><span id="pushPill" class="pill">Kontrollin</span></div><div class="training-actions"><button id="pushToggle" class="btn btn-primary" onclick="togglePush()">Luba teavitused</button></div></div><div class="section"><h2>Teavituste ajalugu</h2><small>${state.notifications.length}</small></div><div class="stack">${state.notifications.map(notificationRow).join('')||'<div class="empty">Teavitusi pole veel.</div>'}</div>`}
function notificationRow(n){return `<div class="notification ${n.read_at?'':'unread'}"><div class="notif-dot ${n.read_at?'read':''}"></div><div><div class="notif-title">${esc(n.title)}</div><div class="notif-body">${esc(n.body)}</div><div class="notif-time">${esc(dateTime(n.created_at))}</div></div></div>`}
async function markNotificationsRead(){try{await rpc('wod_mark_notifications_read',{p_ids:null});state.notifications.forEach(n=>n.read_at=n.read_at||new Date().toISOString());render();toast('Teavitused märgitud loetuks')}catch(e){toast(e.message)}}

function renderMore(){return `<div class="page-head"><div><h1 class="page-title">Veel</h1><div class="page-sub">Profiil, jagamine ja rakenduse seaded.</div></div></div><div class="card"><div class="card-title-row"><div><div class="card-title">${esc(state.profile.display_name)}</div><div class="card-sub">${esc(state.session.user.email||'')} · ${isTrainer()?'Treener':'Klient'}</div></div><span class="pill dark">CF</span></div></div><div class="section"><h2>Rakendus</h2></div><div class="menu-list"><button class="menu-item" onclick="openProfileEdit()"><div class="menu-main"><div class="menu-icon">${icon.user}</div><div><div class="menu-label">Minu profiil</div><div class="menu-desc">Muuda kuvatavat nime</div></div></div><span class="chev">›</span></button><button class="menu-item" onclick="openShare()"><div class="menu-main"><div class="menu-icon">${icon.share}</div><div><div class="menu-label">Kutsu sõber</div><div class="menu-desc">Jaga CrossFiti kutselinki</div></div></div><span class="chev">›</span></button><button class="menu-item" onclick="installApp()"><div class="menu-main"><div class="menu-icon">${icon.plus}</div><div><div class="menu-label">Paigalda rakendus</div><div class="menu-desc">Lisa CrossFit telefoni või arvutisse</div></div></div><span class="chev">›</span></button><button class="menu-item" onclick="openInfo()"><div class="menu-main"><div class="menu-icon">${icon.info}</div><div><div class="menu-label">Rakenduse info</div><div class="menu-desc">Versioon ja kasutuspõhimõtted</div></div></div><span class="chev">›</span></button><button class="menu-item" onclick="logout()"><div class="menu-main"><div class="menu-icon">${icon.logout}</div><div><div class="menu-label">Logi välja</div><div class="menu-desc">Lõpeta selle seadme sessioon</div></div></div><span class="chev">›</span></button></div>`}

function renderModal(){if(!state.modal)return'';const close=`<button class="sheet-close" onclick="closeModal()" aria-label="Sulge">×</button>`;let title='',body='';
  if(state.modal==='training'){const t=state.trainings.find(x=>x.id===state.modalData);if(!t)return'';title='Treening';body=trainingDetail(t)}
  else if(state.modal==='trainingForm'){title=state.modalData?.id?'Muuda treeningut':'Lisa treening';body=trainingForm(state.modalData||{})}
  else if(state.modal==='client'){const p=state.profiles.find(x=>x.user_id===state.modalData);if(!p)return'';title='Kliendikaart';body=clientDetail(p)}
  else if(state.modal==='assignPackage'){title='Lisa pakett';body=assignPackageForm(state.modalData)}
  else if(state.modal==='packageType'){title=state.modalData?.id?'Muuda paketti':'Uus pakett';body=packageTypeForm(state.modalData||{})}
  else if(state.modal==='share'){title='Kutsu sõber CrossFiti';body=shareSheet()}
  else if(state.modal==='calendar'){title='Lisa kalendrisse';body=calendarSheet(state.modalData)}
  else if(state.modal==='profile'){title='Minu profiil';body=profileForm()}
  else if(state.modal==='info'){title='CrossFit';body=infoSheet()}
  else if(state.modal==='quick'){title='Kiirtoimingud';body=quickSheet()}
  return `<div class="sheet-backdrop" onclick="backdropClose(event)"><div class="sheet" onclick="event.stopPropagation()"><div class="sheet-head"><div class="sheet-title">${title}</div>${close}</div><div class="sheet-body">${body}</div></div></div>`
}
function closeModal(){state.modal=null;state.modalData=null;render()}
function backdropClose(e){if(e.target.classList.contains('sheet-backdrop'))closeModal()}

function openTraining(id){state.modal='training';state.modalData=Number(id);render()}
function trainingDetail(t){const c=confirmedFor(t.id),w=waitlistFor(t.id),mine=mineFor(t.id),past=new Date(t.starts_at)<=now(),deadline=cancellationDeadline(t),late=deadline<now();let action='';
  if(isTrainer()) action=`<div class="training-actions"><button class="btn btn-soft" onclick="openTrainingForm(${t.id})">Muuda</button><button class="btn btn-soft" onclick="copyTraining(${t.id})">Kopeeri</button>${t.status!=='cancelled'&&!past?`<button class="btn btn-danger" onclick="cancelTraining(${t.id})">Tühista</button>`:''}<button class="btn btn-danger" onclick="deleteTraining(${t.id})">Kustuta</button></div>`;
  else if(!past&&t.status==='published'){
    if(mine) action=`<div class="detail-block"><h3>Sinu registreering</h3><div class="training-meta">${mine.status==='waitlist'?`<span class="pill amber">Ootenimekiri #${waitPosition(t.id)}</span>`:'<span class="pill green">Registreeritud</span>'}${paymentPill(mine.payment_status)}</div><div class="training-actions"><button class="btn btn-soft" onclick="openCalendar(${t.id})">Lisa kalendrisse</button><button class="btn btn-danger" onclick="cancelRegistration(${t.id})">Tühista registreering</button></div>${mine.status==='confirmed'&&late?'<div class="card-sub" style="margin-top:8px;color:#9b3d43">Tasuta tühistamise aeg on möödas. Tühistada saab, kuid treeningkorda või tasu ei tagastata.</div>':''}</div>`;
    else {const hasPackage=totalCredits()>0||activeUserPackages().some(p=>p.kind==='unlimited'),full=c.length>=t.capacity;action=`<div class="detail-block"><h3>${full?'Treening on täis':'Registreeru'}</h3><div class="card-sub">${full?'Saad liituda ootenimekirjaga. Koha vabanemisel liigud automaatselt trenni.':'Vali, kuidas soovid treeningu eest arvestada.'}</div><div class="training-actions">${hasPackage?`<button class="btn btn-primary" onclick="registerTraining(${t.id},true)">${full?'Ootenimekirja paketiga':'Kasuta paketti'}</button>`:''}<button class="btn btn-soft" onclick="registerTraining(${t.id},false)">${full?'Liitu ootenimekirjaga':'Registreeru · tasun eraldi'}</button></div></div>`}
  }
  const workout=t.workout?`<div class="detail-block"><h3>Päeva treening / WOD</h3><div class="detail-text">${esc(t.workout)}</div></div>`:'';
  const note=t.note?`<div class="detail-block"><h3>Treeneri märkus</h3><div class="detail-text">${esc(t.note)}</div></div>`:'';
  const people=isTrainer()||!past?`<div class="detail-block"><h3>Registreerunud (${c.length}/${t.capacity})</h3><div class="person-list">${c.map(r=>personRow(r,t)).join('')||'<div class="card-sub">Keegi pole veel registreerunud.</div>'}</div>${w.length?`<h3 style="margin-top:14px">Ootenimekiri (${w.length})</h3><div class="person-list">${w.map((r,i)=>personRow(r,t,i+1)).join('')}</div>`:''}</div>`:'';
  return `<div class="detail-hero"><div class="detail-date">${esc(fullDateTime(t.starts_at))}</div><h2>${esc(t.title)}</h2><div class="detail-stats"><div class="detail-stat"><b>${c.length}/${t.capacity}</b><span>Kohti</span></div><div class="detail-stat"><b>${t.duration_minutes}</b><span>Minutit</span></div><div class="detail-stat"><b>${money(t.price_cents)}</b><span>Hind</span></div></div></div><div class="detail-block"><h3>Tühistamise reegel</h3><div class="detail-text">${esc(cancellationRule(t))}</div><div class="card-sub">Tasuta tühistamise tähtaeg: ${esc(fullDateTime(deadline.toISOString()))}</div></div>${workout}${note}${people}${action}`
}
function personRow(r,t,pos=null){return `<div class="person"><div><div class="person-name">${pos?pos+'. ':''}${esc(pname(r.user_id))}</div><div class="person-meta">${r.status==='waitlist'?'Ootenimekirjas':r.cancelled_late?'Hilinenud tühistus':'Registreeritud'}</div><div class="training-meta">${paymentPill(r.payment_status)}</div></div>${isTrainer()&&r.status==='confirmed'&&r.payment_status!=='package'?`<div class="person-actions"><button class="btn btn-sm ${r.payment_status==='paid'?'btn-soft':'btn-green'}" onclick="setPayment(${r.id},${r.payment_status!=='paid'})">${r.payment_status==='paid'?'Märgi tasumata':'Märgi tasutuks'}</button></div>`:''}</div>`}

function openTrainingForm(idOrData=null){let data={};if(typeof idOrData==='number'){const t=state.trainings.find(x=>x.id===idOrData);if(t)data={...t,id:t.id}}else if(idOrData&&typeof idOrData==='object')data=idOrData;state.modal='trainingForm';state.modalData=data;render()}
function localParts(iso){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(iso));const o={};parts.forEach(p=>{if(p.type!=='literal')o[p.type]=p.value});return {date:`${o.year}-${o.month}-${o.day}`,time:`${o.hour}:${o.minute}`}}
function timeOptions(selected='19:00'){let out='';for(let h=6;h<=22;h++)for(const m of [0,15,30,45]){const v=`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;out+=`<option ${v===selected?'selected':''}>${v}</option>`}return out}
function trainingForm(d){const parts=d.starts_at?localParts(d.starts_at):{date:new Intl.DateTimeFormat('en-CA',{timeZone:TZ}).format(new Date(Date.now()+86400000)),time:'19:00'};return `<div class="form"><div class="form-grid"><div class="field"><label>Kuupäev</label><input id="tfDate" type="date" value="${parts.date}"></div><div class="field"><label>Kellaaeg (Eesti aeg)</label><select id="tfTime">${timeOptions(parts.time)}</select></div></div><div class="field"><label>Nimetus</label><input id="tfTitle" value="${esc(d.title||'CrossFit')}"></div><div class="form-grid"><div class="field"><label>Kestus (min)</label><input id="tfDuration" type="number" min="15" max="240" step="5" value="${d.duration_minutes||60}"></div><div class="field"><label>Kohti</label><input id="tfCapacity" type="number" min="1" max="100" value="${d.capacity||12}"></div></div><div class="form-grid"><div class="field"><label>Hind (€)</label><input id="tfPrice" type="number" min="0" step="1" value="${Number(d.price_cents??500)/100}"></div><div class="field"><label>Tasuta tühistamine (h enne)</label><input id="tfCancel" type="number" min="0" max="72" value="${d.cancellation_hours??4}"></div></div><div class="field"><label>Päeva treening / WOD</label><textarea id="tfWorkout" placeholder="Näiteks: 5 rounds...">${esc(d.workout||'')}</textarea></div><div class="field"><label>Treeneri märkus</label><textarea id="tfNote" placeholder="Mida klient peaks enne trenni teadma?">${esc(d.note||'')}</textarea></div>${d.id?'':`<div class="card" style="box-shadow:none"><div class="card-title">Korduv treening</div><div class="card-sub">Soovi korral loo sama treening mitmeks nädalaks.</div><div class="form-grid" style="margin-top:10px"><div class="field"><label>Nädalaid</label><input id="tfWeeks" type="number" min="1" max="12" value="1"></div><div class="field"><label>Nädalapäevad</label><div style="display:flex;gap:5px;flex-wrap:wrap">${[['E',1],['T',2],['K',3],['N',4],['R',5],['L',6],['P',7]].map(([n,v])=>`<label class="pill" style="padding:8px"><input class="tfDay" type="checkbox" value="${v}"> ${n}</label>`).join('')}</div></div></div></div>`}<div class="form-actions"><button class="btn btn-primary" onclick="saveTrainingForm(${d.id||'null'})">${d.id?'Salvesta muudatused':'Avalda treening'}</button><button class="btn btn-soft" onclick="closeModal()">Katkesta</button></div></div>`}
function tallinnLocalToIso(date,time){const guess=new Date(`${date}T${time}:00Z`);const fmt=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});const parts=fmt.formatToParts(guess),o={};parts.forEach(p=>{if(p.type!=='literal')o[p.type]=p.value});const rendered=Date.UTC(+o.year,+o.month-1,+o.day,+o.hour,+o.minute,+o.second),offset=rendered-guess.getTime();return new Date(guess.getTime()-offset).toISOString()}
function addDays(dateStr,n){const [y,m,d]=dateStr.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d+n));return x.toISOString().slice(0,10)}
function weekday(dateStr){const [y,m,d]=dateStr.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d)).getUTCDay();return x===0?7:x}
async function saveTrainingForm(id){const date=document.getElementById('tfDate').value,time=document.getElementById('tfTime').value,title=document.getElementById('tfTitle').value.trim(),duration=+document.getElementById('tfDuration').value,capacity=+document.getElementById('tfCapacity').value,price=Math.round(+document.getElementById('tfPrice').value*100),cancel=+document.getElementById('tfCancel').value,workout=document.getElementById('tfWorkout').value.trim(),note=document.getElementById('tfNote').value.trim();if(!date||!time||!title||capacity<1){toast('Kontrolli treeningu andmeid');return}try{if(id){await api(`wod_trainings?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({title,starts_at:tallinnLocalToIso(date,time),duration_minutes:duration,capacity,price_cents:price,cancellation_hours:cancel,workout:workout||null,note:note||null,updated_at:new Date().toISOString()})})}else{const weeks=Math.max(1,Math.min(12,+document.getElementById('tfWeeks')?.value||1)),days=[...document.querySelectorAll('.tfDay:checked')].map(x=>+x.value),baseWd=weekday(date),chosen=days.length?days:[baseWd],rows=[];for(let w=0;w<weeks;w++){for(const wd of chosen){const delta=w*7+(wd-baseWd);if(delta<0&&w===0)continue;const d=addDays(date,delta);rows.push({created_by:state.session.user.id,title,starts_at:tallinnLocalToIso(d,time),duration_minutes:duration,capacity,price_cents:price,cancellation_hours:cancel,workout:workout||null,note:note||null,status:'published'})}}await api('wod_trainings',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(rows)})}state.modal=null;state.modalData=null;await reloadData(id?'Treening uuendatud':'Treening avaldatud')}catch(e){toast(e.message)}}
function copyTraining(id){const t=state.trainings.find(x=>x.id===id);if(!t)return;const d={...t};delete d.id;const p=localParts(t.starts_at);d.starts_at=tallinnLocalToIso(addDays(p.date,7),p.time);openTrainingForm(d)}
function copyLatestTraining(){const list=[...state.trainings].sort((a,b)=>new Date(b.starts_at)-new Date(a.starts_at));if(!list.length){openTrainingForm();return}copyTraining(list[0].id)}
async function cancelTraining(id){if(!confirm('Tühistada see treening? Registreerunutele saadetakse teavitus ja paketiga tasutud korrad tagastatakse.'))return;try{await rpc('wod_cancel_training',{p_training_id:id});state.modal=null;await reloadData('Treening tühistatud')}catch(e){toast(e.message)}}
async function deleteTraining(id){if(!confirm('Kustutada treening lõplikult? Seda ei saa tagasi võtta.'))return;try{await api(`wod_trainings?id=eq.${id}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});state.modal=null;await reloadData('Treening kustutatud')}catch(e){toast(e.message)}}
async function registerTraining(id,useCredit){try{await rpc('wod_register',{p_training_id:id,p_use_credit:useCredit});await reloadData('Registreerimine õnnestus');state.modal='training';state.modalData=id;render()}catch(e){toast(e.message)}}
async function cancelRegistration(id){const t=state.trainings.find(x=>x.id===id),late=t&&cancellationDeadline(t)<now();const text=late?'Tasuta tühistamise aeg on möödas. Tühistamisel treeningkorda või tasu ei tagastata. Kas jätkata?':'Kas tühistada registreering?';if(!confirm(text))return;try{await rpc('wod_cancel_registration',{p_training_id:id});await reloadData(late?'Registreering tühistatud hilise tühistusena':'Registreering tühistatud');state.modal='training';state.modalData=id;render()}catch(e){toast(e.message)}}
async function setPayment(regId,paid){try{await rpc('wod_set_registration_payment',{p_registration_id:regId,p_paid:paid});await reloadData(paid?'Märgitud tasutuks':'Märgitud tasumata');render()}catch(e){toast(e.message)}}

function openClient(uid){state.modal='client';state.modalData=uid;render()}
function clientDetail(p){const uid=p.user_id,pkgs=state.userPackages.filter(x=>x.user_id===uid),regs=state.registrations.filter(r=>r.user_id===uid),future=regs.filter(r=>['confirmed','waitlist'].includes(r.status)&&state.trainings.some(t=>t.id===r.training_id&&new Date(t.starts_at)>now())).sort((a,b)=>new Date(state.trainings.find(t=>t.id===a.training_id)?.starts_at)-new Date(state.trainings.find(t=>t.id===b.training_id)?.starts_at)),past=regs.filter(r=>r.status==='confirmed'&&state.trainings.some(t=>t.id===r.training_id&&new Date(t.starts_at)<now()&&t.status!=='cancelled')).length,unpaid=regs.filter(r=>r.status==='confirmed'&&r.payment_status==='unpaid').length;return `<div class="card"><div class="card-title-row"><div><div class="card-title">${esc(p.display_name)}</div><div class="card-sub">${past} osaletud treeningut</div></div><span class="pill ${unpaid?'amber':'green'}">${unpaid?unpaid+' tasumata':'Maksed korras'}</span></div><div class="metric-grid" style="margin-top:12px;margin-bottom:0">${metric(totalCredits(uid)===Infinity?'∞':totalCredits(uid),'Kordi alles')}${metric(future.length,'Tulevasi')}${metric(past,'Osaletud')}</div></div><div class="section"><h2>Paketid</h2><button class="btn-link" onclick="openAssignPackage('${uid}')">+ Lisa</button></div><div class="stack">${pkgs.map(packageCard).join('')||'<div class="empty">Kliendil ei ole pakette.</div>'}${legacyCredits(uid)?`<div class="package-card"><div class="package-top"><div><div class="package-name">Varasemad treeningkorrad</div><div class="package-meta">Käsitsi hallatav krediidijääk</div></div><div class="package-balance">${legacyCredits(uid)}</div></div><div class="training-actions"><button class="btn btn-soft btn-sm" onclick="adjustCredits('${uid}',1)">+1</button><button class="btn btn-soft btn-sm" onclick="adjustCredits('${uid}',-1)">−1</button></div></div>`:''}</div><div class="section"><h2>Tulevased registreeringud</h2></div><div class="stack">${future.map(r=>registrationRow(r)).join('')||'<div class="empty">Tulevasi registreeringuid ei ole.</div>'}</div>`}
async function adjustCredits(uid,delta){const reason=prompt('Muudatuse põhjus:',delta>0?'Treener lisas treeningkorra':'Treener eemaldas treeningkorra');if(!reason)return;try{await rpc('wod_adjust_credits',{p_user_id:uid,p_delta:delta,p_reason:reason,p_amount_cents:null});await reloadData('Treeningkorrad uuendatud');state.modal='client';state.modalData=uid;render()}catch(e){toast(e.message)}}

function openAssignPackage(uid){state.modal='assignPackage';state.modalData=uid;render()}
function assignPackageForm(uid){const p=state.profiles.find(x=>x.user_id===uid),types=state.packageTypes.filter(x=>x.active);return `<div class="card"><div class="card-title">${esc(p?.display_name||'Klient')}</div><div class="card-sub">Vali pakett, mis kliendile aktiveeritakse.</div></div><div class="form" style="margin-top:12px"><div class="field"><label>Pakett</label><select id="apType">${types.map(x=>`<option value="${x.id}">${esc(x.name)} · ${money(x.price_cents)}</option>`).join('')}</select></div><div class="field"><label>Tegelik makstud hind (€)</label><input id="apPrice" type="number" min="0" step="1" placeholder="Vaikimisi paketi hind"></div><div class="form-actions"><button class="btn btn-primary" onclick="assignPackage('${uid}')">Aktiveeri pakett</button><button class="btn btn-soft" onclick="closeModal()">Katkesta</button></div></div>`}
async function assignPackage(uid){const typeId=+document.getElementById('apType').value,priceRaw=document.getElementById('apPrice').value,price=priceRaw===''?null:Math.round(+priceRaw*100);try{await rpc('wod_assign_package',{p_user_id:uid,p_package_type_id:typeId,p_price_paid_cents:price});await reloadData('Pakett aktiveeritud');state.modal='client';state.modalData=uid;render()}catch(e){toast(e.message)}}

function openPackageTypeForm(id=null){const p=id?state.packageTypes.find(x=>x.id===id):{};state.modal='packageType';state.modalData=p||{};render()}
function packageTypeForm(p){return `<div class="form"><div class="field"><label>Paketi nimi</label><input id="ptName" value="${esc(p.name||'')}"></div><div class="field"><label>Tüüp</label><select id="ptKind" onchange="togglePackageCredits()"><option value="credits" ${p.kind!=='unlimited'?'selected':''}>Kordadega pakett</option><option value="unlimited" ${p.kind==='unlimited'?'selected':''}>Piiramatu kuupakett</option></select></div><div id="ptCreditsWrap" class="field ${p.kind==='unlimited'?'hidden':''}"><label>Treeningkordi</label><input id="ptCredits" type="number" min="1" value="${p.credits||10}"></div><div class="form-grid"><div class="field"><label>Hind (€)</label><input id="ptPrice" type="number" min="0" step="1" value="${Number(p.price_cents||0)/100}"></div><div class="field"><label>Kehtivus (päeva)</label><input id="ptValidity" type="number" min="1" placeholder="Tühi = tähtajatu" value="${p.validity_days||''}"></div></div><div class="field"><label><input id="ptActive" type="checkbox" ${p.active!==false?'checked':''}> Aktiivne ja klientidele määratav</label></div><div class="form-actions"><button class="btn btn-primary" onclick="savePackageType(${p.id||'null'})">Salvesta</button><button class="btn btn-soft" onclick="closeModal()">Katkesta</button></div></div>`}
function togglePackageCredits(){document.getElementById('ptCreditsWrap')?.classList.toggle('hidden',document.getElementById('ptKind').value==='unlimited')}
async function savePackageType(id){const name=document.getElementById('ptName').value.trim(),kind=document.getElementById('ptKind').value,credits=kind==='credits'?+document.getElementById('ptCredits').value:null,price=Math.round(+document.getElementById('ptPrice').value*100),validRaw=document.getElementById('ptValidity').value,validity=validRaw?+validRaw:null,active=document.getElementById('ptActive').checked;if(!name||(kind==='credits'&&credits<1)){toast('Kontrolli paketi andmeid');return}const body={name,kind,credits,price_cents:price,validity_days:validity,active,updated_at:new Date().toISOString()};try{if(id)await api(`wod_package_types?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});else await api('wod_package_types',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({...body,created_by:state.session.user.id,sort_order:state.packageTypes.length*10})});state.modal=null;await reloadData('Pakett salvestatud')}catch(e){toast(e.message)}}

function openCalendar(id){state.modal='calendar';state.modalData=id;render()}
function calendarSheet(id){const t=state.trainings.find(x=>x.id===id);if(!t)return'';return `<div class="card"><div class="card-title">${esc(t.title)}</div><div class="card-sub">${esc(fullDateTime(t.starts_at))}</div></div><div class="training-actions"><button class="btn btn-primary" onclick="openGoogleCalendar(${id})">Google Calendar</button><button class="btn btn-soft" onclick="downloadIcs(${id})">Apple / Outlook (.ics)</button></div>`}
function openGoogleCalendar(id){const t=state.trainings.find(x=>x.id===id);if(!t)return;const start=new Date(t.starts_at),end=new Date(start.getTime()+Number(t.duration_minutes||60)*60000),fmt=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const q=new URLSearchParams({action:'TEMPLATE',text:t.title,dates:`${fmt(start)}/${fmt(end)}`,details:[t.workout,t.note].filter(Boolean).join('\n\n')});window.open(`https://calendar.google.com/calendar/render?${q.toString()}`,'_blank')}
function icsEscape(s){return String(s||'').replace(/\\/g,'\\\\').replace(/,/g,'\\,').replace(/;/g,'\\;').replace(/\n/g,'\\n')}
function downloadIcs(id){const t=state.trainings.find(x=>x.id===id);if(!t)return;const start=new Date(t.starts_at),end=new Date(start.getTime()+Number(t.duration_minutes||60)*60000),fmt=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const ics=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//CrossFit//ET\r\nBEGIN:VEVENT\r\nUID:crossfit-${t.id}@karlkirch.github.io\r\nDTSTAMP:${fmt(new Date())}\r\nDTSTART:${fmt(start)}\r\nDTEND:${fmt(end)}\r\nSUMMARY:${icsEscape(t.title)}\r\nDESCRIPTION:${icsEscape([t.workout,t.note,cancellationRule(t)].filter(Boolean).join('\n\n'))}\r\nURL:${APP_URL}\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`;const blob=new Blob([ics],{type:'text/calendar;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`CrossFit-${localParts(t.starts_at).date}.ics`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Kalendrifail loodud')}

function openShare(){state.modal='share';state.modalData=null;render()}
function shareSheet(){return `<div class="card"><div class="card-title">Kutsu sõber treeningutele</div><div class="card-sub">Sõber saab lingist konto luua, treeninguid vaadata ja registreeruda.</div></div><div class="training-actions"><button class="btn btn-primary btn-block" onclick="nativeShare()">Jaga telefonist</button></div><div class="share-apps" style="margin-top:10px"><button class="btn btn-soft" onclick="shareVia('whatsapp')">WhatsApp</button><button class="btn btn-soft" onclick="shareVia('messenger')">Messenger</button><button class="btn btn-soft" onclick="shareVia('viber')">Viber</button><button class="btn btn-soft" onclick="shareVia('instagram')">Instagram</button><button class="btn btn-dark" onclick="copyInvite()">Kopeeri kutselink</button></div>`}
const inviteText=()=>`Tule meie CrossFit treeningutele! Vaata treeninguaegu ja registreeru:`;
async function copyInvite(show=true){try{await navigator.clipboard.writeText(APP_URL);if(show)toast('Kutselink kopeeritud')}catch(_){prompt('Kopeeri CrossFiti link:',APP_URL)}}
async function nativeShare(){try{if(navigator.share){await navigator.share({title:'CrossFit',text:inviteText(),url:APP_URL});closeModal()}else{await copyInvite();closeModal()}}catch(e){if(e.name!=='AbortError')toast('Jagamine ebaõnnestus')}}
async function shareVia(app){const combined=`${inviteText()} ${APP_URL}`;if(app==='whatsapp')location.href=`https://wa.me/?text=${encodeURIComponent(combined)}`;else if(app==='messenger'){await copyInvite(false);location.href=`fb-messenger://share/?link=${encodeURIComponent(APP_URL)}`;setTimeout(()=>toast('Link kopeeritud – kleebi see Messengerisse'),500)}else if(app==='viber')location.href=`viber://forward?text=${encodeURIComponent(combined)}`;else{await copyInvite(false);toast('Link kopeeritud – kleebi see Instagrami sõnumisse')}}

function openProfileEdit(){state.modal='profile';render()}
function profileForm(){return `<div class="form"><div class="field"><label>Kuvatav nimi</label><input id="pfName" value="${esc(state.profile.display_name)}"></div><div class="field"><label>E-post</label><input value="${esc(state.session.user.email||'')}" disabled></div><div class="form-actions"><button class="btn btn-primary" onclick="saveProfile()">Salvesta</button><button class="btn btn-soft" onclick="closeModal()">Katkesta</button></div></div>`}
async function saveProfile(){const name=document.getElementById('pfName').value.trim();if(!name){toast('Nimi ei saa olla tühi');return}try{await api(`wod_profiles?user_id=eq.${state.session.user.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({display_name:name})});state.profile.display_name=name;const p=state.profiles.find(x=>x.user_id===state.session.user.id);if(p)p.display_name=name;state.modal=null;render();toast('Profiil uuendatud')}catch(e){toast(e.message)}}
function openInfo(){state.modal='info';render()}
function infoSheet(){return `<div class="card"><div class="card-title">CrossFit treeningurakendus</div><div class="card-sub">Registreerimine, ootenimekiri, paketid, makseolek ja teavitused.</div><div style="margin-top:10px"><div class="info-row"><span>Versioon</span><b>${APP_VERSION}</b></div><div class="info-row"><span>Osalemine</span><b>Registreeritud ja tühistamata = osales</b></div><div class="info-row"><span>Hiline tühistus</span><b>Treeningkorda/tasu ei tagastata</b></div><div class="info-row"><span>Makselahendus</span><b>Käsitsi, automaatne makse hiljem</b></div></div></div>`}
function openQuickActions(){state.modal='quick';render()}
function quickSheet(){return `<div class="quick-grid"><button class="quick" onclick="openTrainingForm()">${icon.plus}<b>Lisa treening</b><span>Üksik või korduv</span></button><button class="quick" onclick="copyLatestTraining()">${icon.copy}<b>Kopeeri eelmine</b><span>Loo kiiresti uus aeg</span></button><button class="quick" onclick="state.modal=null;go('people');toast('Vali klient ja lisa talle pakett')">${icon.package}<b>Lisa pakett</b><span>Vali klient</span></button></div>`}

function pushSupported(){return 'serviceWorker'in navigator&&'PushManager'in window&&typeof Notification!=='undefined'}
function urlBase64ToUint8Array(s){const pad='='.repeat((4-s.length%4)%4),base=(s+pad).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function getAppRegistration(){let reg=await navigator.serviceWorker.getRegistration('/Crossfit/');if(!reg)reg=await navigator.serviceWorker.register('./sw.js?v=4',{scope:'./',updateViaCache:'none'});return reg}
async function pushRequest(path,opt={}){return api(path,opt)}
async function cleanupOldWodSubscription(){try{const old=await navigator.serviceWorker.getRegistration('/Futbol/wod/');const sub=await old?.pushManager?.getSubscription();if(sub){await api(`wod_push_subscriptions?endpoint=eq.${encodeURIComponent(sub.endpoint)}`,{method:'DELETE'}).catch(()=>{});await sub.unsubscribe()}}catch(_){}}
async function enablePush(){if(state.pushBusy)return;state.pushBusy=true;try{if(!pushSupported())throw new Error('See brauser ei toeta push-teavitusi.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error(permission==='denied'?'Teavitused on brauseris blokeeritud.':'Teavituste luba ei antud.');await cleanupOldWodSubscription();const reg=await getAppRegistration();let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(VAPID_PUBLIC)});const j=sub.toJSON();await api('wod_push_subscriptions?on_conflict=endpoint',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:state.session.user.id,endpoint:sub.endpoint,p256dh:j.keys?.p256dh||'',auth:j.keys?.auth||'',updated_at:new Date().toISOString()})});toast('Teavitused on lubatud');render()}catch(e){toast(e.message)}finally{state.pushBusy=false;updatePushStateSoon(true)}}
async function disablePush(){if(state.pushBusy)return;state.pushBusy=true;try{const reg=await getAppRegistration(),sub=await reg.pushManager.getSubscription();if(sub){await api(`wod_push_subscriptions?endpoint=eq.${encodeURIComponent(sub.endpoint)}`,{method:'DELETE'}).catch(()=>{});await sub.unsubscribe()}toast('Teavitused on välja lülitatud');render()}catch(e){toast(e.message)}finally{state.pushBusy=false;updatePushStateSoon(true)}}
async function togglePush(){try{const reg=await getAppRegistration(),sub=await reg.pushManager.getSubscription();if(sub&&Notification.permission==='granted')await disablePush();else await enablePush()}catch(e){toast(e.message)}}
function updatePushStateSoon(force=false){if(state.view!=='notifications')return;setTimeout(()=>refreshPushUI(force),60)}
async function refreshPushUI(){const text=document.getElementById('pushText'),pill=document.getElementById('pushPill'),btn=document.getElementById('pushToggle');if(!text||!pill||!btn)return;if(!pushSupported()){text.textContent='See brauser ei toeta push-teavitusi.';pill.textContent='Pole toetatud';pill.className='pill red';btn.disabled=true;return}if(Notification.permission==='denied'){text.textContent='Teavitused on brauseri seadetes blokeeritud.';pill.textContent='Blokeeritud';pill.className='pill red';btn.textContent='Luba brauseri seadetes';btn.disabled=true;return}try{const reg=await getAppRegistration(),sub=await reg.pushManager.getSubscription(),on=!!sub&&Notification.permission==='granted';text.textContent=on?'Saad teate meeldetuletuse, muudatuse, tühistamise ja ootenimekirjast koha saamise kohta.':'Luba teavitused, et tähtsad muudatused ei jääks märkamata.';pill.textContent=on?'Lubatud':'Väljas';pill.className=`pill ${on?'green':''}`;btn.textContent=on?'Lülita teavitused välja':'Luba teavitused';btn.className=`btn ${on?'btn-soft':'btn-primary'}`}catch(_){text.textContent='Teavituste olekut ei õnnestunud kontrollida.'}}

async function installApp(){if(matchMedia('(display-mode: standalone)').matches||navigator.standalone===true){toast('CrossFit on juba paigaldatud');return}if(state.installPrompt){state.installPrompt.prompt();const r=await state.installPrompt.userChoice;if(r.outcome==='accepted')toast('CrossFit paigaldati');state.installPrompt=null;return}if(/iPhone|iPad|iPod/i.test(navigator.userAgent))alert('iPhone/iPad: vajuta brauseris Jaga ja vali „Lisa avakuvale“.');else alert('Chrome/Edge: ava brauseri menüü ja vali „Installi rakendus“ või „Lisa avakuvale“.')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e});
window.addEventListener('appinstalled',()=>{state.installPrompt=null;toast('CrossFit on paigaldatud')});

async function setupServiceWorker(){if(!('serviceWorker'in navigator))return;try{const reg=await navigator.serviceWorker.register('./sw.js?v=4',{scope:'./',updateViaCache:'none'});state.swReg=reg;if(reg.waiting&&navigator.serviceWorker.controller)showUpdateBanner();reg.addEventListener('updatefound',()=>{const w=reg.installing;if(!w)return;w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)showUpdateBanner()})});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())}catch(e){console.warn('SW registration failed',e)}}
function showUpdateBanner(){updateBanner.classList.remove('hidden')}
updateNow.addEventListener('click',()=>{if(state.swReg?.waiting)state.swReg.waiting.postMessage({type:'SKIP_WAITING'});else location.reload()});

async function logout(){try{if(state.session?.access_token)await fetch(`${SUPABASE_URL}/auth/v1/logout`,{method:'POST',headers:headers(state.session.access_token)})}catch(_){}localStorage.removeItem('wod_session');state.session=null;state.profile=null;state.trainings=[];state.registrations=[];state.profiles=[];state.wallets=[];state.creditTransactions=[];state.packageTypes=[];state.userPackages=[];state.notifications=[];state.view='home';renderAuth()}

function parseAuthHash(){if(!location.hash)return null;const p=new URLSearchParams(location.hash.slice(1)),access=p.get('access_token'),refresh=p.get('refresh_token');if(!access||!refresh)return null;const expires=Number(p.get('expires_in')||3600);return {access_token:access,refresh_token:refresh,expires_in:expires,token_type:p.get('token_type')||'bearer',user:null}}
async function fetchCurrentUser(){const r=await request(`${SUPABASE_URL}/auth/v1/user`,{headers:headers(state.session.access_token)});state.session.user=r;localStorage.setItem('wod_session',JSON.stringify(state.session))}
async function boot(){setupServiceWorker();document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.modal)closeModal()});try{const hash=parseAuthHash();if(hash){state.session=hash;await fetchCurrentUser();history.replaceState(null,'',location.pathname+location.search)}else{const raw=localStorage.getItem('wod_session');if(raw)state.session=JSON.parse(raw)}if(state.session){if(state.session.refresh_token){const ok=await refreshSession();if(!ok){renderAuth();return}}if(!state.session.user)await fetchCurrentUser();await ensureProfile();await loadData();render();return}}catch(e){console.warn(e);localStorage.removeItem('wod_session');state.session=null}renderAuth()}

Object.assign(window,{go,setAuthMode,submitAuth,setTrainingTab,openTraining,openTrainingForm,saveTrainingForm,copyTraining,copyLatestTraining,cancelTraining,deleteTraining,registerTraining,cancelRegistration,setPayment,openClient,adjustCredits,openAssignPackage,assignPackage,openPackageTypeForm,togglePackageCredits,savePackageType,openCalendar,openGoogleCalendar,downloadIcs,openShare,nativeShare,shareVia,copyInvite,openProfileEdit,saveProfile,openInfo,openQuickActions,closeModal,backdropClose,markNotificationsRead,togglePush,installApp,logout,toast,state,reloadData});
boot();
